version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80" # puerto de phpMyAdmin
    networks:
      - mynetwork

  web-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-1
    ports:
      - "8080:80" # Mapear el puerto 80 del contenedor al puerto 8080 de tu máquina
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - mynetwork

  web-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-2
    ports:
      - "8082:80" # Segunda instancia del servicio web
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: citas
    ports:
      - "3306:3306" # Exponer el puerto de MySQL
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8083:80" # Balanceador de cargas en el puerto 8083
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Configuración personalizada de Nginx
    depends_on:
      - web-1
      - web-2
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
